---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by thsheep.
--- DateTime: 2018/5/22 上午9:25
--- 这个lua脚本是为了代替集群中不支持的multi事务；保证在获取的同时删除
---

local result = redis.call('zrange', KEYS[1], 0, 0)
if result[1] then
    redis.call('zremrangebyrank', KEYS[1], 0, 0)
    return result[1]
else
    return nil
end